name: deploy
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v6
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true
    - name: build site
      env:
        API_URL: ${{ secrets.API_URL }}
        FRONTEND_ROOT: ${{ secrets.FRONTEND_ROOT }}
      run: bundle exec weaver build --root=$FRONTEND_ROOT
    - name: artifact site
      id: upload
      uses: actions/upload-pages-artifact@v5
      with:
        path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.upload.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

'on':
  push:
    branches:
    - '*'
